#!/usr/bin/env bash
# Deploy the avatar-onboarding foundation and write the .env contract used by later modules.
#
# Usage:
#   ./deploy.sh <resource-group> [location] [resource-token]
#
# Keyless by design: no keys are read or written. Sign in with `az login` first.
# The default location is a region that supports Speech avatar + Voice Live at time of
# writing; always re-verify region support (see lesson 01) before you commit to one.
set -euo pipefail

RESOURCE_GROUP="${1:-}"
LOCATION="${2:-westus2}"
RESOURCE_TOKEN="${3:-}"

if [[ -z "${RESOURCE_GROUP}" ]]; then
  echo "usage: $0 <resource-group> [location] [resource-token]" >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ACCELERATOR_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE="${ACCELERATOR_DIR}/main.bicep"
ENV_FILE="${ACCELERATOR_DIR}/.env"

if [[ -z "${RESOURCE_TOKEN}" ]]; then
  # Deterministic, lowercase, <=12 chars so storage/search names stay valid.
  RESOURCE_TOKEN="a$(echo -n "${RESOURCE_GROUP}" | sha1sum | cut -c1-9)"
fi

# Grant the signed-in engineer keyless data-plane access (incl. the Speech data plane).
PRINCIPAL_ID="$(az ad signed-in-user show --query id -o tsv 2>/dev/null || echo '')"

echo "==> Resource group: ${RESOURCE_GROUP} (${LOCATION})"
az group create --name "${RESOURCE_GROUP}" --location "${LOCATION}" --output none

echo "==> Validating template"
az deployment group validate \
  --resource-group "${RESOURCE_GROUP}" \
  --template-file "${TEMPLATE}" \
  --parameters resourceToken="${RESOURCE_TOKEN}" location="${LOCATION}" principalId="${PRINCIPAL_ID}" \
  --output none

echo "==> Deploying onboarding foundation (this takes a few minutes)"
az deployment group create \
  --name "avatar-onboarding-$(date +%Y%m%d%H%M%S)" \
  --resource-group "${RESOURCE_GROUP}" \
  --template-file "${TEMPLATE}" \
  --parameters resourceToken="${RESOURCE_TOKEN}" location="${LOCATION}" principalId="${PRINCIPAL_ID}" \
  --query 'properties.outputs' \
  --output json > "${ACCELERATOR_DIR}/.deployment-outputs.json"

echo "==> Writing ${ENV_FILE}"
python3 - "${ACCELERATOR_DIR}/.deployment-outputs.json" "${ENV_FILE}" <<'PY'
import json
import sys

outputs_path, env_path = sys.argv[1], sys.argv[2]
with open(outputs_path, encoding="utf-8") as handle:
    outputs = json.load(handle)

lines = [
    "# Generated by scenarios/avatar-onboarding/accelerator/scripts/deploy.sh",
    "# Keyless: no secrets are written here.",
]
for key, entry in sorted(outputs.items()):
    lines.append(f"{key.upper()}={entry['value']}")
# Tracing switches must be set before importing the Foundry SDK (see lesson 07).
lines.append("AZURE_EXPERIMENTAL_ENABLE_GENAI_TRACING=true")
lines.append("OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT=true")

with open(env_path, "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines) + "\n")
print(f"wrote {len(lines)} lines to {env_path}")
PY

echo "==> Done. Verify against your resources using the checks in lessons/02-foundation.md (## Verify)."
